In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("financial_dataset.csv")

In [3]:
df

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
0,11317,CUST1134,Anjali,Furniture,1875.0,4126.0,16,Pending,Mumbai,2026-10-21 00:00:00
1,11001,CUST1177,Sneha,Stationery,32521.0,9290.0,13,Paid,Bangalore,2026-05-16 00:00:00
2,11069,CUST1478,Sneha,food,8948.0,8683.0,3,Unpaid,Chennai,2026-06-19 00:00:00
3,11968,CUST1016,Priya,Furniture,20072.0,8320.0,1,Pending,Mumbai,2027-09-11 12:00:00
4,10530,CUST1321,Priya,Stationery,32943.0,9336.0,3,Paid,Bangalore,2025-09-22 12:00:00
...,...,...,...,...,...,...,...,...,...,...
1995,10700,CUST1427,Rahul,Electronics,14407.0,9016.0,8,paid,Bangalore,2025-12-16 12:00:00
1996,11500,CUST1136,Neha,Electronics,2105.0,5292.0,13,Unpaid,Delhi,2027-01-20 12:00:00
1997,11706,CUST1247,Vivek,Food,35927.0,2756.0,5,Pending,Mangalore,2027-05-03 12:00:00
1998,10511,CUST1299,Rahul,Furniture,48447.0,1654.0,7,Unpaid,Delhi,2025-09-13 00:00:00
1999,11083,CUST1075,Arun,Clothing,8433.0,4718.0,5,Pending,Kochi,2026-06-26 00:00:00

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    2000 non-null   int64
 1   Customer_ID       2000 non-null   object
 2   Customer_Name     2000 non-null   object
 3   Category          1977 non-null   object
 4   Sales             1967 non-null   float64
 5   Profit            1970 non-null   float64
 6   Quantity          2000 non-null   int64
 7   Payment_Status    2000 non-null   object
 8   City              1979 non-null   object
 9   Transaction_Date  2000 non-null   object
dtypes: float64(2), int64(2), object(6)
memory usage: 156.4+ KB

In [25]:
df["Transaction_Date"]=pd.to_datetime(df["Transaction_ID"],errors='coerce')
df.dtypes

Transaction_ID      datetime64[ns]
Customer_ID                 object
Customer_Name               object
Category                    object
Sales                      float64
Profit                     float64
Quantity                     int64
Payment_Status              object
City                        object
Transaction_Date    datetime64[ns]
dtype: object

In [26]:
df.head()

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
0,1970-01-01 00:00:00.000011317,CUST1134,Anjali,Furniture,1875.0,4126.0,16,Pending,Mumbai,1970-01-01 00:00:00.000011317
1,1970-01-01 00:00:00.000011001,CUST1177,Sneha,Stationery,32521.0,9290.0,13,Paid,Bangalore,1970-01-01 00:00:00.000011001
2,1970-01-01 00:00:00.000011069,CUST1478,Sneha,food,8948.0,8683.0,3,Unpaid,Chennai,1970-01-01 00:00:00.000011069
3,1970-01-01 00:00:00.000011968,CUST1016,Priya,Furniture,20072.0,8320.0,1,Pending,Mumbai,1970-01-01 00:00:00.000011968
4,1970-01-01 00:00:00.000010530,CUST1321,Priya,Stationery,32943.0,9336.0,3,Paid,Bangalore,1970-01-01 00:00:00.000010530

In [27]:
df.tail()

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
1995,1970-01-01 00:00:00.000010700,CUST1427,Rahul,Electronics,14407.0,9016.0,8,paid,Bangalore,1970-01-01 00:00:00.000010700
1996,1970-01-01 00:00:00.000011500,CUST1136,Neha,Electronics,2105.0,5292.0,13,Unpaid,Delhi,1970-01-01 00:00:00.000011500
1997,1970-01-01 00:00:00.000011706,CUST1247,Vivek,Food,35927.0,2756.0,5,Pending,Mangalore,1970-01-01 00:00:00.000011706
1998,1970-01-01 00:00:00.000010511,CUST1299,Rahul,Furniture,48447.0,1654.0,7,Unpaid,Delhi,1970-01-01 00:00:00.000010511
1999,1970-01-01 00:00:00.000011083,CUST1075,Arun,Clothing,8433.0,4718.0,5,Pending,Kochi,1970-01-01 00:00:00.000011083

In [28]:
df.describe()

,Transaction_ID,Sales,Profit,Quantity,Transaction_Date
count,2000,1967.000000,1970.000000,2000.00000,2000
mean,1970-01-01 00:00:00.000011001,25147.046263,3469.098985,10.18850,1970-01-01 00:00:00.000011001
min,1970-01-01 00:00:00.000010001,516.000000,-4982.000000,1.00000,1970-01-01 00:00:00.000010001
25%,1970-01-01 00:00:00.000010502,12723.500000,-812.500000,5.00000,1970-01-01 00:00:00.000010502
50%,1970-01-01 00:00:00.000010998,25200.000000,3526.000000,10.00000,1970-01-01 00:00:00.000010998
75%,1970-01-01 00:00:00.000011504,37545.000000,7711.250000,15.00000,1970-01-01 00:00:00.000011504
max,1970-01-01 00:00:00.000012,49923.000000,11988.000000,19.00000,1970-01-01 00:00:00.000012
std,NaN,14375.624741,4923.386360,5.52958,NaN

In [29]:
df.shape

(2000, 10)

In [30]:
df[df["Category"].str.upper() == "FOOD"]

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
2,1970-01-01 00:00:00.000011069,CUST1478,Sneha,food,8948.0,8683.0,3,Unpaid,Chennai,1970-01-01 00:00:00.000011069
13,1970-01-01 00:00:00.000011622,CUST1161,Anjali,Food,45159.0,-3037.0,9,Paid,Kochi,1970-01-01 00:00:00.000011622
14,1970-01-01 00:00:00.000010071,CUST1053,Anjali,Food,4291.0,5151.0,19,Pending,Chennai,1970-01-01 00:00:00.000010071
18,1970-01-01 00:00:00.000011392,CUST1459,Sneha,Food,26837.0,6375.0,19,Paid,Bangalore,1970-01-01 00:00:00.000011392
20,1970-01-01 00:00:00.000010066,CUST1316,Rohan,Food,19956.0,3747.0,18,Paid,Mumbai,1970-01-01 00:00:00.000010066
...,...,...,...,...,...,...,...,...,...,...
1985,1970-01-01 00:00:00.000011268,CUST1083,Sneha,food,43740.0,-1218.0,11,Paid,Delhi,1970-01-01 00:00:00.000011268
1988,1970-01-01 00:00:00.000010563,CUST1444,Sneha,FOOD,16472.0,11892.0,5,Pending,Mangalore,1970-01-01 00:00:00.000010563
1989,1970-01-01 00:00:00.000011992,CUST1372,Vivek,Food,3208.0,10702.0,4,Pending,Chennai,1970-01-01 00:00:00.000011992
1993,1970-01-01 00:00:00.000011807,CUST1235,Priya,food,19057.0,5394.0,5,Unpaid,Mangalore,1970-01-01 00:00:00.000011807
1997,1970-01-01 00:00:00.000011706,CUST1247,Vivek,Food,35927.0,2756.0,5,Pending,Mangalore,1970-01-01 00:00:00.000011706

In [31]:
df[df["Payment_Status"] == "Paid"]

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
1,1970-01-01 00:00:00.000011001,CUST1177,Sneha,Stationery,32521.0,9290.0,13,Paid,Bangalore,1970-01-01 00:00:00.000011001
4,1970-01-01 00:00:00.000010530,CUST1321,Priya,Stationery,32943.0,9336.0,3,Paid,Bangalore,1970-01-01 00:00:00.000010530
6,1970-01-01 00:00:00.000010415,CUST1384,Neha,Electronics,19594.0,-1484.0,10,Paid,Chennai,1970-01-01 00:00:00.000010415
8,1970-01-01 00:00:00.000010417,CUST1135,Anjali,Clothing,2157.0,-1445.0,13,Paid,Mumbai,1970-01-01 00:00:00.000010417
11,1970-01-01 00:00:00.000011576,CUST1313,Rahul,Electronics,30522.0,10540.0,18,Paid,Bangalore,1970-01-01 00:00:00.000011576
...,...,...,...,...,...,...,...,...,...,...
1987,1970-01-01 00:00:00.000011900,CUST1491,Sneha,Furniture,14701.0,-1799.0,12,Paid,Bangalore,1970-01-01 00:00:00.000011900
1990,1970-01-01 00:00:00.000010687,CUST1384,Anjali,Stationery,16895.0,1207.0,8,Paid,Mangalore,1970-01-01 00:00:00.000010687
1991,1970-01-01 00:00:00.000010958,CUST1178,Rohan,Clothing,25441.0,-1094.0,18,Paid,Mangalore,1970-01-01 00:00:00.000010958
1992,1970-01-01 00:00:00.000010190,CUST1179,Arun,Stationery,14498.0,4513.0,1,Paid,Delhi,1970-01-01 00:00:00.000010190
1994,1970-01-01 00:00:00.000010976,CUST1046,Sneha,Clothing,48791.0,2866.0,8,Paid,Delhi,1970-01-01 00:00:00.000010976

In [32]:
df[(df["Sales"] > 40000) & (df["Payment_Status"] == "Pending")]

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
12,1970-01-01 00:00:00.000010252,CUST1234,Vivek,Clothing,47659.0,-1956.0,10,Pending,Mumbai,1970-01-01 00:00:00.000010252
23,1970-01-01 00:00:00.000011269,CUST1042,Vivek,Food,46260.0,11343.0,5,Pending,Delhi,1970-01-01 00:00:00.000011269
40,1970-01-01 00:00:00.000011264,CUST1264,Anjali,Furniture,45929.0,3428.0,7,Pending,Bangalore,1970-01-01 00:00:00.000011264
47,1970-01-01 00:00:00.000010255,CUST1463,Priya,Electronics,46425.0,6593.0,15,Pending,Bangalore,1970-01-01 00:00:00.000010255
56,1970-01-01 00:00:00.000011002,CUST1267,Anjali,Furniture,43332.0,2776.0,10,Pending,Chennai,1970-01-01 00:00:00.000011002
...,...,...,...,...,...,...,...,...,...,...
1896,1970-01-01 00:00:00.000011699,CUST1288,Vivek,Electronics,48422.0,-2044.0,3,Pending,Mangalore,1970-01-01 00:00:00.000011699
1938,1970-01-01 00:00:00.000010202,CUST1237,Priya,Stationery,42729.0,-2377.0,11,Pending,Mangalore,1970-01-01 00:00:00.000010202
1951,1970-01-01 00:00:00.000011026,CUST1358,Neha,Furniture,46012.0,5661.0,17,Pending,Delhi,1970-01-01 00:00:00.000011026
1953,1970-01-01 00:00:00.000011896,CUST1491,Vivek,Furniture,45740.0,-3561.0,6,Pending,Delhi,1970-01-01 00:00:00.000011896
1977,1970-01-01 00:00:00.000010841,CUST1170,Rahul,Food,47434.0,5694.0,1,Pending,Delhi,1970-01-01 00:00:00.000010841

In [33]:
df[df["City"] == "Mumbai"]

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
0,1970-01-01 00:00:00.000011317,CUST1134,Anjali,Furniture,1875.0,4126.0,16,Pending,Mumbai,1970-01-01 00:00:00.000011317
3,1970-01-01 00:00:00.000011968,CUST1016,Priya,Furniture,20072.0,8320.0,1,Pending,Mumbai,1970-01-01 00:00:00.000011968
5,1970-01-01 00:00:00.000011450,CUST1435,Vivek,Stationery,5533.0,-3177.0,4,Unpaid,Mumbai,1970-01-01 00:00:00.000011450
8,1970-01-01 00:00:00.000010417,CUST1135,Anjali,Clothing,2157.0,-1445.0,13,Paid,Mumbai,1970-01-01 00:00:00.000010417
12,1970-01-01 00:00:00.000010252,CUST1234,Vivek,Clothing,47659.0,-1956.0,10,Pending,Mumbai,1970-01-01 00:00:00.000010252
...,...,...,...,...,...,...,...,...,...,...
1961,1970-01-01 00:00:00.000011479,CUST1254,Anjali,Clothing,14298.0,NaN,3,Pending,Mumbai,1970-01-01 00:00:00.000011479
1966,1970-01-01 00:00:00.000010898,CUST1369,Vivek,Food,17741.0,-2491.0,18,Paid,Mumbai,1970-01-01 00:00:00.000010898
1972,1970-01-01 00:00:00.000010316,CUST1201,Neha,NaN,42722.0,629.0,8,Unpaid,Mumbai,1970-01-01 00:00:00.000010316
1978,1970-01-01 00:00:00.000010021,CUST1150,Vivek,Furniture,9019.0,2853.0,13,Pending,Mumbai,1970-01-01 00:00:00.000010021
1981,1970-01-01 00:00:00.000011509,CUST1095,Arun,Clothing,25400.0,534.0,4,Unpaid,Mumbai,1970-01-01 00:00:00.000011509

In [34]:
df.sort_values('Profit')

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
1152,1970-01-01 00:00:00.000010138,CUST1472,Vivek,Furniture,27823.0,-4982.0,10,Paid,Kochi,1970-01-01 00:00:00.000010138
1891,1970-01-01 00:00:00.000011514,CUST1282,Rahul,Furniture,1393.0,-4979.0,7,Paid,Kochi,1970-01-01 00:00:00.000011514
527,1970-01-01 00:00:00.000011084,CUST1435,Sneha,Clothing,38744.0,-4972.0,5,Pending,Chennai,1970-01-01 00:00:00.000011084
1924,1970-01-01 00:00:00.000010720,CUST1215,Priya,Furniture,43669.0,-4952.0,6,Unpaid,Bangalore,1970-01-01 00:00:00.000010720
62,1970-01-01 00:00:00.000011898,CUST1446,Neha,Stationery,41264.0,-4945.0,5,Pending,Mangalore,1970-01-01 00:00:00.000011898
...,...,...,...,...,...,...,...,...,...,...
1686,1970-01-01 00:00:00.000010208,CUST1160,Sneha,Clothing,46540.0,NaN,16,Paid,Mumbai,1970-01-01 00:00:00.000010208
1703,1970-01-01 00:00:00.000011929,CUST1101,Neha,Electronics,30935.0,NaN,13,Unpaid,Kochi,1970-01-01 00:00:00.000011929
1834,1970-01-01 00:00:00.000010525,CUST1391,Anjali,Food,25506.0,NaN,16,Pending,Mumbai,1970-01-01 00:00:00.000010525
1961,1970-01-01 00:00:00.000011479,CUST1254,Anjali,Clothing,14298.0,NaN,3,Pending,Mumbai,1970-01-01 00:00:00.000011479
1984,1970-01-01 00:00:00.000010832,CUST1442,Rahul,Stationery,14752.0,NaN,7,Pending,Kochi,1970-01-01 00:00:00.000010832

In [35]:
df.sort_values('Sales')

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
69,1970-01-01 00:00:00.000010549,CUST1063,Neha,Stationery,516.0,-4882.0,11,Pending,Kochi,1970-01-01 00:00:00.000010549
1945,1970-01-01 00:00:00.000011846,CUST1237,Rohan,Electronics,560.0,257.0,5,Unpaid,Chennai,1970-01-01 00:00:00.000011846
888,1970-01-01 00:00:00.000011457,CUST1179,Sneha,Stationery,566.0,9772.0,2,Unpaid,Delhi,1970-01-01 00:00:00.000011457
1869,1970-01-01 00:00:00.000011763,CUST1234,Vivek,Clothing,645.0,-3637.0,4,Unpaid,Chennai,1970-01-01 00:00:00.000011763
1192,1970-01-01 00:00:00.000011482,CUST1322,Priya,Stationery,678.0,-4596.0,6,Paid,Mumbai,1970-01-01 00:00:00.000011482
...,...,...,...,...,...,...,...,...,...,...
1780,1970-01-01 00:00:00.000011292,CUST1350,Rohan,Stationery,NaN,7886.0,7,Paid,Bangalore,1970-01-01 00:00:00.000011292
1803,1970-01-01 00:00:00.000011769,CUST1020,Sneha,Clothing,NaN,9688.0,2,Pending,Mumbai,1970-01-01 00:00:00.000011769
1822,1970-01-01 00:00:00.000010796,CUST1339,Vivek,Stationery,NaN,-4934.0,1,Unpaid,Chennai,1970-01-01 00:00:00.000010796
1885,1970-01-01 00:00:00.000010201,CUST1231,Priya,Furniture,NaN,3534.0,17,Unpaid,Chennai,1970-01-01 00:00:00.000010201
1949,1970-01-01 00:00:00.000011414,CUST1165,Arun,Electronics,NaN,9195.0,7,Paid,Kochi,1970-01-01 00:00:00.000011414

In [36]:
sales_report=df.groupby("Category").agg(
        Total_Revenue=("Sales", "sum"),
        Total_Profit=("Profit", "sum"),
)
print(sales_report)

             Total_Revenue  Total_Profit
Category
Clothing         9844177.0     1374186.0
Electronics      8390788.0     1104818.0
FOOD              420537.0       44420.0
Food             9751908.0     1344231.0
Furniture       10214137.0     1342336.0
Stationery       9547483.0     1416727.0
food              718585.0      121393.0

In [37]:
customer_summeries=df.groupby(["Customer_ID", "Customer_Name"]).agg(
        Gross_Spend=("Sales", "sum"),
        Net_Profit=("Profit", "sum"),
        Total_Transactions=("Transaction_ID", "count"),
        Avg_Items=("Quantity", "mean"),
)
print(customer_summeries)

                           Gross_Spend  Net_Profit_Contribution  \
Customer_ID Customer_Name
CUST1001    Anjali             26279.0                   3174.0
            Priya              92702.0                   3726.0
            Rohan              27651.0                   4867.0
            Sneha              76707.0                  13469.0
CUST1002    Anjali             42074.0                  -3993.0
...                                ...                      ...
CUST1499    Rohan              61949.0                  -6042.0
CUST1500    Anjali             12272.0                   3998.0
            Priya              28729.0                  10369.0
            Rohan              65878.0                   3108.0
            Sneha              59021.0                   8570.0

                           Total_Transactions  Avg_Items_Per_Order
Customer_ID Customer_Name
CUST1001    Anjali                          2             2.000000
            Priya                           3            11.333333
            Rohan                           1             8.000000
            Sneha                           2            11.500000
CUST1002    Anjali                          1             4.000000
...                                       ...                  ...
CUST1499    Rohan                           2            12.000000
CUST1500    Anjali                          1            19.000000
            Priya                           1            11.000000
            Rohan                           2            12.000000
            Sneha                           3            15.000000

[1537 rows x 4 columns]

In [38]:
pd.pivot_table(
    df,
    values="Profit",
    index="City",
    columns="Category",
    aggfunc="sum",
    fill_value=0.0,
    margins=True, 
    margins_name="Total_Profit",
)

Category,Clothing,Electronics,FOOD,Food,Furniture,Stationery,food,Total_Profit
City,,,,,,,,
Bangalore,282295.0,172666.0,7184.0,184445.0,199066.0,269748.0,23835.0,1139239.0
Chennai,195850.0,248529.0,4308.0,296867.0,199119.0,274224.0,42022.0,1260919.0
Delhi,231836.0,229418.0,13318.0,245670.0,219765.0,236584.0,10046.0,1186637.0
Kochi,156372.0,181375.0,-3221.0,201015.0,253415.0,230251.0,17577.0,1036784.0
Mangalore,301680.0,126549.0,11922.0,269682.0,200965.0,238515.0,19133.0,1168446.0
Mumbai,196887.0,124225.0,10909.0,144753.0,231247.0,168804.0,8780.0,885605.0
Total_Profit,1364920.0,1082762.0,44420.0,1342432.0,1303577.0,1418126.0,121393.0,6677630.0